### PR TITLE
Add latest survey paper

### PR DESCRIPTION
**Pull request by lwaekfjlk**

### CODE REVIEW

**Comment by ProKil** [comment]
Hi @lwaekfjlk Thanks for contributing! Would you mind following https://sotopia-lab.github.io/awesome-social-agents/contribution?

**Comment by lwaekfjlk** [comment]
Thanks! Can you add this contribution file as a CONTRIBUTION.md in the main repo?

**Comment by ProKil** [comment]
hi any updates on this?

**Comment by lwaekfjlk** [comment]
one sec. update in an hour.

**Comment by lwaekfjlk** [comment]
Redo in #49.

**Pull request closed without merging**
