### PR TITLE
Added a few papers

### PR DESCRIPTION
**Pull request by neubig**
Added papers on a survey on persuasive technology and the AI wolf contest in Japan.

### CODE REVIEW

**Comment by ProKil** [comment]
@neubig Is this still WIP? Not pushing, but I could help with tagging and adding URL.

**Comment by neubig** [comment]
I'll add more stuff later and figure it out, Thu/Fri was busy with the workshop and today I'm flying to ICLR

**Comment by neubig** [comment]
@ProKil this is ready for review.

**Review by ProKil — APPROVED** [review]

**Comment by ProKil** [comment]
Thanks @neubig for your contribution!

**Pull request merged**
